### PR TITLE
python shockwave extractor

### PR DESCRIPTION
**Pull request by MrBrax**
very experimental, does not export all files properly, but the majority
works. probably more useful for comparing ideas about the file formats.

also, git is really overcomplicated for what it is, this is a mess

### CODE REVIEW

**Comment by Brian151** [comment]
Alright then

My only problem with the fact it lacks comments is that Schockabsorber also lacks comments and such, and as a result, if not for tomysshadow, it wouldn't be usable by me, because I can't read it

i agree, there's stuff about git/github that... isn't too awesome

**Comment by MrBrax** [comment]
Because of the language barrier? I can try adding some comments to it.

**Comment by Brian151** [comment]
just in general, reading another's code is not always easy. ofc, i only really skimmed yours.
it's still a good idea to comment code. self-documenting code honestly only goes so far.

python i sorta understand?
throw some C/C++/ASM at me, there might be problems

As long as it's not minimized or obfuscated (or strange dialects or manners of writing it), i usually can read:
js,as,haxe,batch,python,java
basically, anything either high level or not inherently difficult. probably even some esolangs (alright, one... I think I could get used to reading FIM++, but it's so under-developed there's no reason for me to take interest)

idk...
i don't have any huge language barriers excluding those that are obscure or arcane. that said, don't for ANY reason write something in brainf--- and expect me to understand. (ironically, i wanna try some stuff concerning it)

i need to sleep now

**Comment by MrBrax** [comment]
true true, that's why i usually don't work with other people haha

i put some comments in, just gotta put the github client on this pc

**Comment by Brian151** [comment]
makes sense i suppose

**Pull request merged**
